name = "jiwonz/glob"
version = "0.1.2"
description = "glob/wildcard filtering utility for lune"
authors = ["jiwonz <me@jiwonz.kr>"]
repository = "https://github.com/jiwonz/glob-lune"
license = "MIT"
includes = ["README.md", "LICENSE", "pesde.toml", "src/**"]

[target]
environment = "lune"
lib = "src/lib.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[engines]
lune = "^0.10.2"
pesde = "^0.7.1"

[dependencies]
globrex_lune = { name = "kimpure/globrex_lune", version = "^0.2.9" }
pathfs = { name = "jiwonz/pathfs", version = "^0.6.0" }
